# SPDX-FileCopyrightText: Nir Soffer <nirsof@gmail.com>
#
# SPDX-License-Identifier: MIT

name: CI
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "pypy-3.8"
          - "pypy-3.9"
          - "pypy-3.10"
        exclude:
          # Warns about old pip.
          - os: macos-latest
            python: "3.8"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install tox
      - run: tox -e py
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # latest stable version
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-a-python-version
          python-version: "3.x"
      - run: pip install tox
      - run: tox -e flake8
